server.port=8080
spring.application.name=bff-service

services.solicitudes.url=http://localhost:8081
services.catalogo.url=http://localhost:8082

# Microsoft Entra ID - Resource Server (validacion de JWT emitido para api-cloud-native)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/06f1c869-7c5f-43b4-95b1-75bf0354d168/
security.oauth2.audience=7442c5c2-5a49-4b98-a70f-b6aec439fd6a
